name: Output event details
on: issues
jobs:
  output-event-details:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: |
          echo "Event : ${{ toJson(github.event) }}"
